# Estágio 1: Build
FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Estágio 2: Servindo com Nginx
FROM nginx:alpine
# Copia o build do estágio anterior para a pasta do Nginx
COPY --from=build /app/build /usr/share/nginx/html
# Copia uma config básica para o React (ajuda com rotas)
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]