
version: '3.8'

services:
  fazenda-impressao:
    build: .
    container_name: Fazenda_3D
    ports:
      - "5000:5000"
    volumes:
      # Mapeia a pasta backend inteira para uma pasta de dados interna
      # Isso garante que arquivos criados pelo Python persistam corretamente
      - ./backend:/app/data
      # Mantém o mapeamento de uploads
      - ./backend/uploads:/app/uploads
    restart: always