
version: '3.8'

services:
  fazenda-impressao:
    build: .
    container_name: Fazenda_3D
    ports:
      - "5000:5000"
    volumes:
      # Persiste o Banco de Dados
      - ./backend/fazenda.db:/app/fazenda.db
      # Persiste a Chave JWT (para não deslogar todo mundo se o container reiniciar)
      - ./backend/.jwt_key:/app/.jwt_key
      # Persiste os arquivos G-Code que as impressoras vão baixar
      - ./backend/uploads:/app/uploads
    restart: always